# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      versionOrBranch:
        required: true
        default: ""
      minorVersion:
        required: true
        default: ""

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run a multi-line script
        env:
          BRANCH: ${{ github.event.inputs.BRANCH }}
          MINOR_VERSION: ${{ github.event.inputs.minorVersion }}
        run: |
          ./make-artifact-bundle.sh ${BRANCH} ${MINOR_VERSION}
